/*
 * generated by Xtext
 */
package eu.scasefp7.eclipse.reqeditor.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRqsDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(eu.scasefp7.eclipse.reqeditor.dsl.rqsDsl.RqsDslPackage.eINSTANCE);
		return result;
	}
}
