/*
 * generated by Xtext
 */
package eu.scasefp7.eclipse.reqeditor.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RqsDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return eu.scasefp7.eclipse.reqeditor.dsl.ui.internal.RqsDslActivator.getInstance().getInjector("eu.scasefp7.eclipse.reqeditor.dsl.RqsDsl");
	}
	
}
