/*
 * generated by Xtext
 */
package eu.scasefp7.eclipse.reqeditor.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RqsDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("eu/scasefp7/eclipse/reqeditor/dsl/parser/antlr/internal/InternalRqsDsl.tokens");
	}
}
