/*
 * generated by Xtext
 */
package eu.scasefp7.eclipse.reqeditor.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RqsDslRuntimeModule extends eu.scasefp7.eclipse.reqeditor.dsl.AbstractRqsDslRuntimeModule {

}
