/*
 * generated by Xtext
 */
package eu.scasefp7.eclipse.reqeditor.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import syntaxcoloring.HighlightingConfiguration;
import syntaxcoloring.SemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RqsDslUiModule extends eu.scasefp7.eclipse.reqeditor.dsl.ui.AbstractRqsDslUiModule {
	public RqsDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
		
	}
	/**
	 * Calculates when to use custom style
	 * 
	 */
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return SemanticHighlightingCalculator.class;
	}
	/**
	 * Provides highlighting styles for xtext editor
	 *
	 */
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
	     return HighlightingConfiguration.class;
	}
}
