/**
 * generated by Xtext
 */
package eu.scasefp7.eclipse.reqeditor.dsl.validation;

import eu.scasefp7.eclipse.reqeditor.dsl.validation.AbstractRqsDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class RqsDslValidator extends AbstractRqsDslValidator {
}
